/** Comic drawing vocabulary. Symbols are original, not a creator's branded assets. */
import {clamp,bezier,tangent,inv,easeInOut} from './motion.mjs';
export const C={paper:'#F5F0E5',ink:'#22252B',muted:'#737972',orange:'#FF7549',yellow:'#FFCF50',teal:'#3CC7B2',blue:'#789DFF',red:'#F06A67',cream:'#FFFDF7',line:'#DCD8CE',purple:'#AAA1DD'};
export function round(ctx,x,y,w,h,r=20,fill=C.cream,stroke=C.ink,lw=4,shadow=0){ctx.save();ctx.lineJoin='round';if(shadow){ctx.fillStyle=C.ink;ctx.beginPath();ctx.roundRect(x+shadow,y+shadow,w,h,r);ctx.fill()}ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke&&lw){ctx.lineWidth=lw;ctx.strokeStyle=stroke;ctx.stroke()}ctx.restore()}
export function line(ctx,points,color=C.ink,width=4,dash=[]){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.setLineDash(dash);ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();ctx.restore()}
export function ellipse(ctx,x,y,rx,ry,fill,stroke=null,lw=4){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
export function text(ctx,str,x,y,size=36,color=C.ink,{align='left',weight=800,font='sans',maxWidth}={}){ctx.save();ctx.font=`${weight} ${size}px ${font==='mono'?'"DejaVu Sans Mono", monospace':'"Noto Sans CJK SC","PingFang SC","Microsoft YaHei",sans-serif'}`;ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(str,x,y,maxWidth);ctx.restore()}
export function label(ctx,str,x,y,{fill=C.cream,size=26,pad=20,height=48,angle=0,shadow=4}={}){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.font=`800 ${size}px "Noto Sans CJK SC",sans-serif`;let w=ctx.measureText(str).width+pad*2;round(ctx,-w/2,-height/2,w,height,12,fill,C.ink,3,shadow);text(ctx,str,0,1,size,C.ink,{align:'center'});ctx.restore();return w}
export function burst(ctx,x,y,r,amount=1,color=C.yellow){ctx.save();ctx.translate(x,y);ctx.fillStyle=color;ctx.strokeStyle=C.ink;ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<24;i++){let a=i/24*Math.PI*2;let rr=(i%2?r*.64:r)*amount;let p=[Math.cos(a)*rr,Math.sin(a)*rr];i?ctx.lineTo(...p):ctx.moveTo(...p)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
export function dots(ctx,x,y,w,h,{step=14,r=1.5,color=C.ink,alpha=.13}={}){ctx.save();ctx.globalAlpha*=alpha;ctx.fillStyle=color;for(let yy=y;yy<y+h;yy+=step)for(let xx=x;xx<x+w;xx+=step){ctx.beginPath();ctx.arc(xx,yy,r,0,Math.PI*2);ctx.fill()}ctx.restore()}
export function path(ctx,points,{color=C.line,width=6,progress=1,dash=[]}={}){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.setLineDash(dash);ctx.beginPath();for(let i=0;i<=100*progress;i++){let p=bezier(points,i/100);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)}ctx.stroke();ctx.restore()}
export function arrowHead(ctx,x,y,a,color=C.ink,size=14){ctx.save();ctx.translate(x,y);ctx.rotate(a);line(ctx,[[-size,-size*.64],[0,0],[-size,size*.64]],color,5);ctx.restore()}
export function packet(ctx,points,t,start,end,{color=C.orange,str='RUN',size=1}={}){if(t<start||t>end)return;const u=easeInOut(inv(t,start,end));const p=bezier(points,u),a=tangent(points,u);ctx.save();for(let j=5;j>0;j--){const pp=bezier(points,clamp(u-j*.02));ctx.globalAlpha=(1-j/6)*.21;ellipse(ctx,pp.x,pp.y,18-j*2,18-j*2,color)}ctx.globalAlpha=1;ctx.translate(p.x,p.y);ctx.rotate(a*.15);ctx.scale(size,size);round(ctx,-70,-29,140,58,15,color,C.ink,4,6);text(ctx,str,0,1,27,C.ink,{align:'center',font:'mono'});ctx.restore()}
export function check(ctx,x,y,s=1,color=C.ink){ctx.save();ctx.translate(x,y);ctx.scale(s,s);line(ctx,[[-18,0],[-4,15],[25,-19]],color,8);ctx.restore()}
export function cross(ctx,x,y,s=1,color=C.ink){line(ctx,[[x-12*s,y-12*s],[x+12*s,y+12*s]],color,6*s);line(ctx,[[x+12*s,y-12*s],[x-12*s,y+12*s]],color,6*s)}
